# Generated by Django 4.2.13 on 2025-02-11 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='Fld_Profile_pic',
            field=models.FileField(blank=True, default='images/Screenshot from 2025-02-10 16-40-49.png', null=True, upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='Tbl_insurance_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fld_Plan_name', models.CharField(max_length=100)),
                ('Fld_Coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fld_Premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fld_Start_date', models.DateField()),
                ('Fld_End_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
