# Generated by Django 4.2.13 on 2025-02-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_tbl_user_fld_profile_pic_tbl_insurance_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_insurance_plan',
            name='Fld_Description',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_insurance_plan',
            name='Fld_Insurance_pic',
            field=models.FileField(blank=True, default='images/Screenshot from 2025-02-10 16-40-49.png', null=True, upload_to='profiles/'),
        ),
    ]
