# Generated by Django 4.2.13 on 2025-02-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_insurance_plan_fld_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_insurance_plan',
            name='Fld_Coverage_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_insurance_plan',
            name='Fld_Premium',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
