# Generated by Django 4.2.13 on 2025-02-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_tbl_insurance_plan_fld_coverage_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_insurance_plan',
            name='Fld_End_date',
        ),
        migrations.RemoveField(
            model_name='tbl_insurance_plan',
            name='Fld_Start_date',
        ),
        migrations.AddField(
            model_name='tbl_insurance_plan',
            name='Fld_Coverage_details',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='tbl_insurance_plan',
            name='Fld_Period',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=7),
        ),
    ]
