# Generated by Django 4.2.13 on 2025-02-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tbl_family_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_insurance_plan',
            name='Fld_Category',
            field=models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('senior', 'Senior Citizens')], default='individual', max_length=20),
        ),
    ]
