# Generated by Django 4.2.13 on 2025-02-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_tbl_insurance_plan_fld_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_family_member',
            name='Fld_Member_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tbl_family_member',
            name='Fld_Plan_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('family', 'Family')], default='individual', max_length=20),
        ),
    ]
