# Generated by Django 4.2.13 on 2025-02-18 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_tbl_family_member_fld_member_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fld_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fld_Date', models.DateTimeField(auto_now_add=True)),
                ('Fld_gst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Fld_Total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('family_members', models.ManyToManyField(to='user.tbl_family_member')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.tbl_insurance_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_PlanExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fld_Expiry_date', models.DateField()),
                ('Fld_Renewal_options', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_insurance_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
