# Generated by Django 4.2.13 on 2025-02-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_tbl_transaction_tbl_planexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_insurance_plan',
            name='Fld_Validity',
            field=models.DateField(default='2025-12-31'),
        ),
    ]
