# Generated by Django 4.2.13 on 2025-02-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Tbl_Comment',
        ),
    ]
