# Generated by Django 4.2.13 on 2025-02-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_comment_tbl_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_transaction',
            name='Fld_Paypal_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
