# Generated by Django 4.2.13 on 2025-02-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_tbl_transaction_fld_paypal_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
