# Generated by Django 4.2.13 on 2025-02-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_tbl_cart_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_family_member',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
