# Generated by Django 4.2.13 on 2025-02-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_tbl_family_member_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_planexpiry',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tbl_planexpiry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tbl_Comment',
        ),
        migrations.DeleteModel(
            name='Tbl_PlanExpiry',
        ),
    ]
