# Generated by Django 4.2.13 on 2025-02-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_tbl_planexpiry_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_transaction',
            name='Fld_Created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
