# Generated by Django 4.2.13 on 2025-02-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_tbl_transaction_fld_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_insurance_plan',
            name='Fld_Status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tbl_insurance_plan',
            name='Fld_Validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
