# Generated by Django 4.2.13 on 2025-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_tbl_insurance_plan_fld_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_transaction',
            name='Fld_Expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
