# Generated by Django 4.2.13 on 2026-05-01 19:54

from django.db import migrations, models
import user.models


def move_default_image_paths(apps, schema_editor):
    TblInsurancePlan = apps.get_model('user', 'Tbl_insurance_plan')
    TblUser = apps.get_model('user', 'Tbl_user')
    old_default = 'images/Screenshot from 2025-02-10 16-40-49.png'

    TblInsurancePlan.objects.filter(Fld_Insurance_pic=old_default).update(
        Fld_Insurance_pic='plan_pic/default-plan.svg'
    )
    TblUser.objects.filter(Fld_Profile_pic=old_default).update(
        Fld_Profile_pic='profile_pic/default-profile.svg'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_tbl_transaction_fld_expiration_date'),
    ]

    operations = [
        migrations.RunPython(move_default_image_paths, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tbl_insurance_plan',
            name='Fld_Insurance_pic',
            field=models.FileField(blank=True, default='plan_pic/default-plan.svg', null=True, storage=user.models.StaticImageStorage(), upload_to='plan_pic/'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='Fld_Profile_pic',
            field=models.FileField(blank=True, default='profile_pic/default-profile.svg', null=True, storage=user.models.StaticImageStorage(), upload_to='profile_pic/'),
        ),
    ]
